### PR TITLE
OPS-414/dock extension feature

### PR DESCRIPTION
**Pull request by 0xOI**
Add dock micro-enviroment extension functionality

    This is the first feature to be introduced a part of the dock
    micro-environment work. It allows users to either create or update an existing image with
    the necessary environment configuration to launch a project within dock.

    Deliverables (following execution):
    - a running container with (volume, port, env var, etc) configuration stored: functions as an extended micro-environment
    - local image containing env var, volume, port, etc. config

### CODE REVIEW

**Comment by johndotpub** [comment]
Please ensure that the CHANGELOG and README are updated accordingly as well as bumping the "dock_version=" to 'unreleased'

We'll cut a v1.4 and tag it after this is merged.

**Comment by 0xOI** [comment]
roger that @z3usy, CHANGELOG and README have been updated accordingly

**Comment by 0xOI** [comment]
Actually, so there's a test that ensures the current version is in a proper format (i.e. [0-9]+\.[0-9]+\....) => so that's a no-go on setting the "dock_version=" to 'unreleased' without modifying tests. Seems like I can just bump the version in bin/dock at the same time we push the new version tags and changes to master though...

**Comment by 0xOI** [comment]
all copacetic, seems like the flow Shane employed should be good:
When merging changes into master:
1. update CHANGELOG with new change description but label as "master (unreleased)"
2. update README if necessary
3. leave version in bin/dock as previous

Following merge and when committing changes to master (in a separate release commit):
1. update CHANGELOG with new version
2. update version in bin/dock with new version
3. commit changes to master with tagging matching new version and commit message 'Release version <new-version>" (e.g. git tag <new-version> -> git push origin master --tags)

**Pull request merged**
